apiVersion: apps/v1
kind: Deployment
metadata:
  name: gvoice-playground
  namespace: gvoice-frontend-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gvoice-playground
  template:
    metadata:
      labels:
        app: gvoice-playground
    spec:
      containers:
        - name: gvoice-playground
          image: gvoicecontainerregistery.azurecr.io/gvoice-demo-playground:latest # ❗ Fixed space after colon
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_LIVEKIT_URL
              value: 'wss://multi-model-testing-px7oa3yv.livekit.cloud'
            - name: NEXT_PUBLIC_LIVEKIT_API_KEY
              value: 'APIizuNPFQftCpv'
            - name: NEXT_PUBLIC_LIVEKIT_API_SECRET
              value: '7TWdOeleD5YvHuDSNHYh2gH4A6QPwmH0VOS9SR6489D'
            - name: 'NEXT_PUBLIC_LIVEKIT_API_NAME'
              value: 'gvoice-agent-test'
            - name: 'NEXT_PUBLIC_LIVEKIT_API_PERSONAL_ASSISTANT'
              value: "gvoice-agent-test3"

            - name: 'NEXT_PUBLIC_GVOICE_PRODUCTION_URL'
              value: 'https://v2.gvoice.galaxytechnologyservices.net'
            - name: 'NEXT_PUBLIC_LANDING_PAGE_URL'
              value: 'https://gvoice.galaxytechnologyservices.net'
      imagePullSecrets:
        - name: gvoice-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gvoice-playground-service
  namespace: gvoice-frontend-apps
spec:
  selector:
    app: gvoice-playground
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gvoice-playground-ingress
  namespace: gvoice-frontend-apps
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - playground.gvoice.gtsg.in  # <-- UPDATE DOMAIN
      secretName: gvoice-playground-tls                   # <-- YOUR TLS SECRET
  rules:
    - host: playground.gvoice.gtsg.in  # <-- UPDATE DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gvoice-playground-service
                port:
                  number: 80


